language: cpp
before_install:
  - wget http://www.cmake.org/files/v3.0/cmake-3.0.0.tar.gz
  - tar xf cmake-3.0.0.tar.gz
  - cd cmake-3.0.0
  - ./configure
  - make
  - make install
compiler:
  - clang
  - gcc
script:
  - mkdir tests/build
  - cd tests/build
  - cmake .. && make
  - ./tests