language: cpp
before_install:
  - sudo apt-get install -y libsdl1.2-dev
  - sudo apt-get install -y libsdl-image1.2-dev
compiler:
  - gcc
script:
  - set -e
  - mkdir tests/build
  - cd tests/build
  - cmake ..
  - make -j8
  - ./tests