language: cpp
before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install cmake
compiler:
  - clang
  - gcc
script:
  - mkdir tests/build
  - cd tests/build
  - cmake .. && make
  - ./tests