SET(spn_include ${CMAKE_CURRENT_LIST_DIR}/include)
SET(spn_src
	./src/async/Timer.cpp
	./src/game/Button.cpp
	./src/game/transition/FadeOut.cpp
	./src/game/transition/ITransition.cpp
	./src/game/transition/FadeIn.cpp
	./src/game/Entity.cpp
	./src/game/Room.cpp
	./src/draw/ScopedColour.cpp
	./src/emitter/Emitter.cpp
	./src/emitter/Particle.cpp
	./src/component/WindowExitCollision.cpp
	./src/component/Position.cpp
	./src/component/ComponentEntity.cpp
	./src/component/Dimensions.cpp
	./src/component/WindowTouchCollision.cpp
	./src/component/Rotation.cpp
	./src/component/Scale.cpp
	./src/component/IComponent.cpp
	./src/component/Velocity.cpp
	./src/component/Colour.cpp
	./src/component/Clickable.cpp
	./src/component/AngularVelocity.cpp
	./src/component/RenderTexture.cpp
	./src/component/RenderTextureCentre.cpp
	./src/component/RenderSheetCustom.cpp
	./src/component/InputConsumer.cpp
	./src/math/Intersect.cpp
	./src/tween/Tween.cpp
	./src/tween/TweenFactory.cpp)